#!/usr/bin/env python3
"""
api_smoke_test.py — verify every HTTP API endpoint works end-to-end.

Requires fastapi + httpx (httpx is a fastapi.testclient dep). If
those aren't installed:
    pip install fastapi httpx --break-system-packages

This uses FastAPI's TestClient which runs the app in-process — no
need for uvicorn or network ports.

Usage:
    python3 api_smoke_test.py
    RB_API_KEY=test python3 api_smoke_test.py   # exercise auth header too

Exits 0 on success, 1 on any failure.
"""
from __future__ import annotations

import os
import sys
import tempfile
import zipfile
from pathlib import Path

SYSTEM_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SYSTEM_DIR / "scripts"))
sys.path.insert(0, str(SYSTEM_DIR / "api"))

try:
    from fastapi.testclient import TestClient
except ImportError:
    sys.stderr.write(
        "fastapi / httpx not installed. Run:\n"
        "  pip install fastapi httpx --break-system-packages\n"
    )
    sys.exit(2)

import server  # noqa: E402

client = TestClient(server.app)
headers = {}
if os.environ.get("RB_API_KEY"):
    headers["x-api-key"] = os.environ["RB_API_KEY"]


GET_CHECKS = [
    ("/health", None),
    ("/daily_brief", None),
    ("/brief/health", None),
    ("/brief/latest-json", None),
    ("/draft-actions", None),
    ("/validate_baseline", None),
    ("/gap_detection", None),
    ("/loops", None),
    ("/network_gap?gaps_only=true&limit=5", None),
    ("/drr_score?limit=5", None),
    ("/drr_score?id=donnie-boivin", None),
    ("/status", None),
    ("/manifest", None),
    ("/protocols", None),
    ("/active_threads", None),
    ("/calendar_overlay", None),
    ("/source_readiness?feed=calendar", None),
    ("/email_overlay", None),
    ("/social_overlay", None),
    ("/social_outbound_overlay", None),
    ("/post_recommendations", None),
    ("/network_analysis", None),
    ("/intro?target=Toast&limit=3", None),
    ("/sessions/recent?limit=2", None),
    ("/relationship_signals", None),
    ("/relationship_signals?hours=48", None),
    ("/strategic_memory", None),
    ("/strategic_memory?q=What%20durable%20restaurant%20AI%20failure%20signals%20do%20we%20have%3F", None),
    ("/smart_loops/proposals", None),
    ("/test_traces/recent?limit=5", None),
]

# POST endpoints exercised in a non-destructive way. Trace writes hit
# system/test_traces/ but never touch baseline or canonical state, so they
# are safe to run in smoke tests.
POST_CHECKS = [
    # Smart-loops apply with confirm=false MUST be a read-shaped, write-free
    # preview. Per the smoke-test-mutations memory, no smoke path can reach a
    # mutation against canonical state without an explicit dry_run/confirm gate.
    ("/smart_loops/apply", {"confirm": False}),
    ("/test_traces", {
        "title": "api_smoke_test trace fixture",
        "trace_type": "smoke_test",
        "source": "api_smoke_test.py",
        "operator": "automation",
        "summary": "Generated by api_smoke_test.py to verify the trace endpoint.",
        "steps": [
            {
                "step": 1,
                "label": "smoke",
                "user_prompt": "smoke",
                "assistant_response": "smoke",
                "intended_operation": "health",
                "endpoint": "GET /health",
                "request_params": {"x-api-key": "do-not-persist-this"},
                "response_status": 200,
                "response_summary": "ok",
            }
        ],
    }),
    ("/opportunity_intake", {
        "confirm": False,
        "event_at": "2026-05-21",
        "contact_name": "Sarah McAngus",
        "referrer_name": "Jeff Staley",
        "company_name": "Foods Connected",
        "opportunity_title": "Commercial Director - North America",
        "stage": "resume_submitted",
        "materials_received": True,
        "resume_submitted": True,
        "prior_food_safety_certification": True,
        "surecheck_story": True,
        "text": (
            "Sarah McAngus connection request and positive call. Jeff Staley "
            "recommended Todd after interviewing with Sarah. Foods Connected "
            "Commercial Director North America role: 70% farming McDonald's and 30% hunting. "
            "Sarah sent JD and website; Todd tailored resume and sent resume. "
            "Todd has food safety certification and PAR SureCheck McDonald's context."
        ),
        "domain_tags": ["McDonald's", "food safety", "traceability", "Ireland-founded", "Bentonville"],
    }),
    ("/strategic_operators/apply", {
        "confirm": False,
        "action": "record_movement",
        "operator_id": "ghai-management",
        "fields": {
            "event_at": "2026-05-23",
            "movement_type": "acquisition",
            "summary": "API smoke dry-run movement; should not write.",
            "source": "api_smoke_test.py",
            "confidence": "medium",
            "inferences": {
                "standardization_pressure": "high"
            }
        }
    }),
]


def _check_card_projection_in_sync(card_id: str = "jeff-wayman"):
    """Read-only assertion: GET /cards/{id} reports canonical == frontmatter.

    Closes TOUCHCONTACT-VALIDATION-CONFLICT-001 — exposes when the materialized
    RC card frontmatter has drifted from the canonical baseline last_touch.
    """
    r = client.get(f"/cards/{card_id}", headers=headers)
    if r.status_code != 200:
        return False, f"GET /cards/{card_id} -> {r.status_code}"
    data = r.json()
    if data.get("projection_status") != "in_sync":
        return (
            False,
            f"projection_status={data.get('projection_status')!r}; "
            f"canonical={data.get('canonical', {}).get('last_touch')!r} "
            f"frontmatter={data.get('frontmatter', {}).get('last_touch')!r}",
        )
    return True, (
        f"in_sync at last_touch={data['canonical']['last_touch']}"
    )


def _check_touch_projection_round_trip(card_id: str = "jeff-wayman"):
    """Round-trip mutation: touch advances baseline + card frontmatter, then
    reverts. Validates the response shape introduced for
    TOUCHCONTACT-PROJECTION-SYNC-001 and leaves canonical state unchanged.
    """
    from datetime import date, timedelta
    # Capture initial state
    r = client.get(f"/cards/{card_id}", headers=headers)
    if r.status_code != 200:
        return False, f"pre-state GET /cards/{card_id} -> {r.status_code}"
    initial = r.json()
    if initial.get("projection_status") != "in_sync":
        return False, f"pre-condition not in_sync: {initial.get('projection_status')}"
    original = initial["canonical"]["last_touch"]
    # Pick a sentinel distinct from `original` so the round-trip exercises a
    # real rewrite. Default: today; fall back to today-1 if today == original.
    new_date = date.today().isoformat()
    if new_date == original:
        new_date = (date.today() - timedelta(days=1)).isoformat()
    # Advance
    r = client.post(
        "/touch", headers=headers, json={"id": card_id, "date": new_date},
    )
    if r.status_code != 200:
        return False, f"advance POST /touch -> {r.status_code}: {r.text[:160]}"
    advance = r.json()
    expected = {
        "ok": True, "id": card_id, "last_touch": new_date,
        "baseline_updated": True, "card_exists": True, "card_updated": True,
    }
    for k, v in expected.items():
        if advance.get(k) != v:
            return False, f"advance response field {k!r}={advance.get(k)!r} (expected {v!r})"
    if advance.get("card_reason") not in ("replaced", "added"):
        return False, f"advance card_reason={advance.get('card_reason')!r}"
    # Verify projection sync after advance
    after = client.get(f"/cards/{card_id}", headers=headers).json()
    if after.get("projection_status") != "in_sync":
        return False, f"post-advance projection_status={after.get('projection_status')!r}"
    if (
        after["canonical"]["last_touch"] != new_date
        or after["frontmatter"]["last_touch"] != new_date
    ):
        return False, (
            f"post-advance values diverged: canonical={after['canonical']['last_touch']!r} "
            f"frontmatter={after['frontmatter']['last_touch']!r}"
        )
    # Revert
    r = client.post(
        "/touch", headers=headers, json={"id": card_id, "date": original},
    )
    if r.status_code != 200:
        return False, f"revert POST /touch -> {r.status_code}: {r.text[:160]}"
    final = client.get(f"/cards/{card_id}", headers=headers).json()
    if (
        final.get("projection_status") != "in_sync"
        or final["canonical"]["last_touch"] != original
        or final["frontmatter"]["last_touch"] != original
    ):
        return False, (
            f"post-revert state inconsistent: status={final.get('projection_status')!r} "
            f"canonical={final['canonical']['last_touch']!r} "
            f"frontmatter={final['frontmatter']['last_touch']!r}"
        )
    return True, f"round-trip OK ({original} -> {new_date} -> {original})"


def _check_linkedin_zip_auto_ingest():
    """Regression for RB 9.0 LinkedIn ZIP auto-routing.

    A known LinkedIn export artifact must classify as linkedin_export_zip and
    the dry-run ingest response must contain deltas, recommendations, and
    visualization data. This is the trust-generating layer that prevents the
    generic "what do you want me to do with this file?" failure.
    """
    fixture = Path(tempfile.gettempdir()) / "rb_api_smoke_linkedin_export.zip"
    with zipfile.ZipFile(fixture, "w") as z:
        z.writestr(
            "Connections.csv",
            "Notes\nMore notes\n"
            "First Name,Last Name,URL,Email Address,Company,Position,Connected On\n"
            "Todd,Lennig,https://www.linkedin.com/in/atoddlennig,,"
            "Southern Tier Bookkeeping and Tax Services,Professional Bookkeeper,29 Apr 2025\n"
            "Smoke,Leader,https://www.linkedin.com/in/smokeleader,,"
            "Restaurant AI Co,Chief Revenue Officer,20 May 2026\n",
        )
        z.writestr("messages.csv", "FROM,TO,DATE,SUBJECT,CONTENT\na,b,2026-05-20,,hello\n")
    r = client.post("/artifacts/classify", headers=headers, json={"path": str(fixture)})
    if r.status_code != 200:
        return False, f"classify -> {r.status_code}: {r.text[:160]}"
    classified = r.json()
    if classified.get("artifact_type") != "linkedin_export_zip":
        return False, f"artifact_type={classified.get('artifact_type')!r}"
    r = client.post(
        "/linkedin/ingest",
        headers=headers,
        json={"path": str(fixture), "ingest_date": "2026-05-21", "dry_run": True},
    )
    if r.status_code != 200:
        return False, f"ingest dry-run -> {r.status_code}: {r.text[:160]}"
    body = r.json()
    required = {
        "summary_markdown": bool(body.get("summary_markdown")),
        "recommended_actions": bool(body.get("recommended_actions")),
        "network_visualization": bool(body.get("network_visualization")),
        "delta_intelligence": bool(body.get("delta_intelligence")),
        "baseline_comparison": "## Baseline Comparison" in (body.get("summary_markdown") or ""),
        "graph_mutations": "## Graph Mutations" in (body.get("summary_markdown") or ""),
        "persistence_verification": "## Persistence Verification" in (body.get("summary_markdown") or ""),
        "new_connections": body.get("headline_counts", {}).get("new_connections") == 1,
    }
    missing = [k for k, ok in required.items() if not ok]
    if missing:
        return False, f"missing/failed fields: {missing}"
    return True, "LinkedIn ZIP classified and dry-run RI enhancement returned deltas/actions/visualization"


# Extra validations that go beyond status-code checks. Each entry is
#   (label, callable -> (ok: bool, message: str))
# These run after the GET/POST status checks.
def _check_smart_loops_apply_no_write_without_confirm():
    """The apply endpoint must not write loops unless confirm=true.

    This is the smoke-level enforcement of the smoke-test-mutations rule and
    P-009 confirmed-execution discipline. We compare the loop-ledger row
    count before and after a confirm=false call; any delta means the gate
    leaked.
    """
    import rb_core
    before = sum(1 for L in rb_core.parse_loop_ledger())
    r = client.post(
        "/smart_loops/apply",
        headers=headers,
        json={"confirm": False},
    )
    if r.status_code != 200:
        return False, f"POST /smart_loops/apply (confirm=false) -> {r.status_code}: {r.text[:160]}"
    body = r.json()
    if body.get("confirmed") is not False:
        return False, f"confirmed={body.get('confirmed')!r} (expected false)"
    if body.get("applied_count", 0) != 0:
        return False, f"applied_count={body.get('applied_count')} (expected 0)"
    after = sum(1 for L in rb_core.parse_loop_ledger())
    if after != before:
        return False, f"loop ledger grew from {before} to {after} rows with confirm=false"
    fresh = body.get("fresh") or []
    if fresh and not all(p.get("apply_status") == "not_confirmed" for p in fresh):
        return False, "at least one fresh proposal missing apply_status='not_confirmed'"
    return True, f"confirm=false preview returned {len(fresh)} fresh proposal(s); ledger unchanged ({before} rows)"


def _check_linkedin_session_reader_ttl():
    import linkedin_session_reader

    rc = linkedin_session_reader.self_test()
    if rc != 0:
        return False, "linkedin_session_reader self-test failed"
    return True, "session capture ingests, materializes, and purges expired posts"


def _check_strategic_memory_starbucks_fixture():
    import strategic_memory

    with tempfile.TemporaryDirectory() as td:
        path = Path(td) / "strategic_memory.json"
        rec = strategic_memory.record(
            "CNBC: Starbucks scrapped an AI inventory tool across North America "
            "after operational accuracy and adoption issues. industry intelligence",
            store_path=path,
        )
        if not rec.get("detected"):
            return False, "strategic memory trigger was not detected"
        answer = strategic_memory.query(
            "What durable restaurant AI failure signals do we have?",
            store_path=path,
        )
        text = answer.get("answer") or ""
        if "Starbucks discontinued an AI inventory tool" not in text:
            return False, "query did not retrieve Starbucks AI inventory failure"
        if "operator trust" not in text:
            return False, "query did not explain operator trust relevance"
    return True, "Starbucks durable restaurant-AI failure signal records and retrieves"


EXTRA_VALIDATIONS = [
    ("cards.jeff-wayman.projection_in_sync", _check_card_projection_in_sync),
    ("touch.jeff-wayman.round_trip", _check_touch_projection_round_trip),
    ("linkedin_zip.auto_ingest_dry_run", _check_linkedin_zip_auto_ingest),
    ("smart_loops.apply_no_write_without_confirm", _check_smart_loops_apply_no_write_without_confirm),
    ("linkedin_session_reader.ttl_purge", _check_linkedin_session_reader_ttl),
    ("strategic_memory.starbucks_fixture", _check_strategic_memory_starbucks_fixture),
]


def run() -> int:
    failures = 0
    total = len(GET_CHECKS) + len(POST_CHECKS) + len(EXTRA_VALIDATIONS)
    print(f"{'endpoint':<60} {'status':<8}")
    print("-" * 75)
    for url, _ in GET_CHECKS:
        try:
            r = client.get(url, headers=headers)
            ok = r.status_code == 200
            print(f"GET {url:<56} {r.status_code:<8}")
            if not ok:
                failures += 1
                print(f"    body: {r.text[:200]}")
        except Exception as e:
            failures += 1
            print(f"GET {url:<56} EXCEPT {type(e).__name__}: {str(e)[:50]}")
    for url, body in POST_CHECKS:
        try:
            r = client.post(url, headers=headers, json=body)
            ok = r.status_code == 200
            print(f"POST {url:<55} {r.status_code:<8}")
            if not ok:
                failures += 1
                print(f"    body: {r.text[:200]}")
            elif url == "/test_traces":
                # Clean up the smoke trace files we just wrote so the
                # test doesn't accumulate debris in system/test_traces/.
                try:
                    data = r.json()
                    for key in ("md_file", "json_file"):
                        rel = data.get(key)
                        if rel:
                            (SYSTEM_DIR.parent / rel).unlink(missing_ok=True)
                except Exception:
                    pass
        except Exception as e:
            failures += 1
            print(f"POST {url:<55} EXCEPT {type(e).__name__}: {str(e)[:50]}")
    for label, fn in EXTRA_VALIDATIONS:
        try:
            ok, msg = fn()
            tag = "OK" if ok else "FAIL"
            print(f"CHK {label:<56} {tag:<8}")
            if not ok:
                failures += 1
                print(f"    {msg}")
            else:
                print(f"    {msg}")
        except Exception as e:
            failures += 1
            print(f"CHK {label:<56} EXCEPT {type(e).__name__}: {str(e)[:80]}")
    print("-" * 75)
    if failures == 0:
        print(f"All {total} endpoints pass.")
        return 0
    print(f"{failures}/{total} failed.")
    return 1


if __name__ == "__main__":
    sys.exit(run())
