#!/usr/bin/env python3
"""Queue one urgent routine-research request when news outruns RB's baseline.

This is the bridge between two intentionally separate cycles.  It does not do
research itself and does not mutate canonical intelligence.  It inspects the
daily cycle's already-persisted material entity signals, measures baseline
coverage, and appends at most one bounded request for the routine-research
automation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import math
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

import account_background_brief as abb  # noqa: E402
import ecosystem_intelligence as ei  # noqa: E402
import intelligence_cascade as cascade  # noqa: E402
import rb_core as core  # noqa: E402
import competitor_intelligence_common as cic  # noqa: E402

REQUESTS_PATH = core.SYSTEM_DIR / "inbox" / "routine_research_requests.jsonl"
RECEIPTS_PATH = core.CACHE_DIR / "routine_research_receipts.jsonl"
CACHE_PATH = core.CACHE_DIR / "baseline_research_gate.json"
BASE_RESEARCH_BUDGET = 3
MAX_RESEARCH_BUDGET = 8
REQUEST_COOLDOWN_DAYS = 14
NEWSWORTHY_TRIGGER_TYPES = {"ecosystem_signal", "entity_alert"}
TRIGGER_FRESHNESS_DAYS = 7


def _trigger_is_current(source: dict, today: date) -> bool:
    """Reject old graph history accidentally surfaced as a current event."""
    if source.get("type") not in NEWSWORTHY_TRIGGER_TYPES:
        return False
    candidates = [source.get("event_date"), source.get("date"), source.get("published_at")]
    source_id = str(source.get("id") or "")
    match = re.search(r"(?:^|-)20\d{2}-\d{2}-\d{2}(?:-|$)", source_id)
    if match:
        candidates.append(match.group(0).strip("-"))
    for raw in candidates:
        if not raw:
            continue
        try:
            observed = date.fromisoformat(str(raw)[:10])
        except ValueError:
            continue
        return today - timedelta(days=TRIGGER_FRESHNESS_DAYS) <= observed <= today
    # Entity-alert records are generated by today's scan and may carry only a
    # count; undated historical ecosystem records are not safe triggers.
    return source.get("type") == "entity_alert"


def _signal_intensity(signal: dict) -> int:
    """Score how strongly today's evidence says the entity is changing now."""
    sources = signal.get("sources") or []
    source_types = {str(row.get("type") or "") for row in sources}
    score = 35 if signal.get("material") else 0
    score += min(30, 12 * len(source_types & NEWSWORTHY_TRIGGER_TYPES))
    score += min(20, 5 * len(sources))
    return min(100, score)


def _strategic_value(entity: dict, graph: dict) -> int:
    """Score durable account value independently from today's signal volume."""
    entity_id = entity.get("id")
    watch_ids = {row.get("entity_id") for row in graph.get("watch_list") or []}
    score = 30 if entity_id in watch_ids else 0
    rank = entity.get("rank") if entity.get("rank") is not None else (entity.get("attributes") or {}).get("rank")
    if isinstance(rank, (int, float)):
        score += 45 if rank <= 100 else 30 if rank <= 500 else 15 if rank <= 1500 else 5
    if (entity.get("entity_type") or entity.get("type")) == "vendor":
        score += 15
    return min(100, score)


def _research_budget(candidate_count: int, already_queued: int) -> int:
    """Scale daily research capacity with verified demand, within safe bounds."""
    if candidate_count <= 0:
        return 0
    desired = max(BASE_RESEARCH_BUDGET, math.ceil(candidate_count / 2))
    return max(0, min(MAX_RESEARCH_BUDGET, desired) - already_queued)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        try:
            value = json.loads(line)
            if isinstance(value, dict):
                rows.append(value)
        except (ValueError, TypeError):
            continue
    return rows


def _append(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, sort_keys=True) + "\n")


def _norm(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def _account_coverage(name: str) -> dict:
    """Measure useful baseline dimensions, not mere shell-file existence."""
    try:
        slug, exists = abb.resolve_account(name)
    except Exception:  # noqa: BLE001
        slug, exists = "", False
    if not exists:
        return {"established": False, "score": 0, "dimensions": [], "slug": None}
    try:
        intel = abb.retrieve_existing_intelligence(slug)
        account = (intel.get("dossier") or {}).get("account") or {}
    except Exception:  # noqa: BLE001
        account = {}
    dimensions = []
    if str(account.get("executive_summary") or "").strip() or str(account.get("current_business_situation") or "").strip():
        dimensions.append("business_context")
    leadership = account.get("leadership") or {}
    if (leadership.get("confirmed") or leadership.get("reported_unverified")):
        dimensions.append("leadership")
    if account.get("technology_stack") or (intel.get("ecosystem_relationships") if 'intel' in locals() else []):
        dimensions.append("technology")
    if account.get("strategic_position") or account.get("opportunities"):
        dimensions.append("strategy")
    # Three dimensions is enough to compare breaking news to a meaningful
    # baseline; a generated-but-empty account shell scores zero.
    return {"established": len(dimensions) >= 3, "score": len(dimensions),
            "dimensions": dimensions, "slug": slug}


def _baseline_coverage(name: str, entity: dict) -> dict:
    """Entity-type-aware baseline sufficiency."""
    entity_type = entity.get("entity_type") or entity.get("type") or "unknown"
    if entity_type == "vendor":
        dimensions = []
        matched_slug = None
        try:
            registry = cic.load_registry()
            for row in registry.get("competitors", registry.get("registry", [])):
                display = row.get("display_name") or row.get("name") or ""
                if _norm(display) == _norm(name):
                    matched_slug = row.get("slug") or row.get("competitor_slug")
                    break
            if matched_slug:
                profile = cic.load_competitor(matched_slug)
                competitor = profile.get("competitor") or {}
                if competitor.get("positioning_summary") or competitor.get("todds_pov"):
                    dimensions.append("market_position")
                if competitor.get("product_lines") or competitor.get("category_battle_cards"):
                    dimensions.append("products_and_categories")
                if profile.get("evidence"):
                    dimensions.append("source_evidence")
                if competitor.get("vs_genius", {}).get("genius_advantages") or competitor.get("vs_genius", {}).get("competitor_advantages"):
                    dimensions.append("competitive_posture")
        except Exception:  # noqa: BLE001
            pass
        return {"established": len(dimensions) >= 3, "score": len(dimensions),
                "dimensions": dimensions, "slug": matched_slug, "baseline_kind": "competitor"}

    coverage = _account_coverage(name)
    dimensions = list(coverage["dimensions"])
    attrs = entity.get("attributes") or {}
    if attrs and "company_profile" not in dimensions:
        dimensions.append("company_profile")
    entity_id = entity.get("id")
    if entity_id and "technology" not in dimensions:
        try:
            graph = ei._read_graph()
            if any(entity_id in (r.get("from_entity_id"), r.get("to_entity_id"))
                   for r in graph.get("relationships", [])):
                dimensions.append("technology")
        except Exception:  # noqa: BLE001
            pass
    coverage.update({"dimensions": dimensions, "score": len(dimensions),
                     "established": len(dimensions) >= 3, "baseline_kind": "account"})
    return coverage


def _recent_research(name: str, today: date) -> bool:
    cutoff = today - timedelta(days=90)
    for row in reversed(_jsonl(RECEIPTS_PATH)):
        if _norm(str(row.get("entity_name") or "")) != _norm(name):
            continue
        completed = str(row.get("completed_at") or "")[:10]
        try:
            return date.fromisoformat(completed) >= cutoff
        except ValueError:
            return False
    return False


def _recent_request(name: str, today: date) -> bool:
    cutoff = today - timedelta(days=REQUEST_COOLDOWN_DAYS)
    for row in reversed(_jsonl(REQUESTS_PATH)):
        if _norm(str(row.get("entity_name") or "")) != _norm(name):
            continue
        queued = str(row.get("queued_at") or "")[:10]
        try:
            return date.fromisoformat(queued) >= cutoff
        except ValueError:
            return False
    return False


def run(today: date) -> dict:
    graph = ei._read_graph()
    entities_by_normalized_name = {
        _norm(str(entity.get("name") or "")): entity
        for entity in graph.get("entities", []) if entity.get("name")
    }
    detected = cascade._entities_with_new_intelligence_today(today.isoformat(), graph)
    already_queued_today = sum(
        1 for row in _jsonl(REQUESTS_PATH)
        if str(row.get("queued_at") or "")[:10] == today.isoformat()
        and row.get("priority") == "urgent_news_baseline_gap"
    )
    candidates = []
    for name, signal in detected.items():
        if not signal.get("material"):
            continue
        trigger_sources = signal.get("sources") or []
        # technomic_promoted is a priority scan roster, not proof that a new
        # article or event exists. Require a real persisted signal or dated
        # alert hit before spending an urgent research unit.
        if not any(_trigger_is_current(source, today) for source in trigger_sources):
            continue
        entity_id = signal.get("entity_id")
        entity = next((e for e in graph.get("entities", []) if e.get("id") == entity_id), {})
        if not entity:
            # Some feeder caches carry only the canonical display name. Exact
            # normalized-name resolution is safe; fuzzy guessing is not.
            entity = entities_by_normalized_name.get(_norm(name), {})
            entity_id = entity.get("id")
        coverage = _baseline_coverage(name, entity)
        if coverage["established"] or _recent_research(name, today) or _recent_request(name, today):
            continue
        signal_intensity = _signal_intensity(signal)
        strategic_value = _strategic_value(entity, graph)
        opportunity_score = round(0.6 * signal_intensity + 0.4 * strategic_value)
        candidates.append({
            "entity_name": name,
            "entity_id": entity_id,
            "entity_type": entity.get("entity_type") or entity.get("type") or "unknown",
            "baseline_coverage": coverage,
            "trigger_sources": trigger_sources,
            "rank": entity.get("rank") if entity.get("rank") is not None else (entity.get("attributes") or {}).get("rank"),
            "signal_intensity": signal_intensity,
            "strategic_value": strategic_value,
            "opportunity_score": opportunity_score,
            "research_lane": "pursuit" if strategic_value >= 30 else "radar_discovery",
        })

    candidates.sort(key=lambda x: (
        -x["opportunity_score"],
        x["baseline_coverage"]["score"],
        x["rank"] if isinstance(x.get("rank"), int) else 999999,
        x["entity_name"].lower(),
    ))
    queued = []
    daily_budget = min(MAX_RESEARCH_BUDGET, max(BASE_RESEARCH_BUDGET, math.ceil(len(candidates) / 2))) if candidates else 0
    remaining_budget = _research_budget(len(candidates), already_queued_today)
    for candidate in candidates[:remaining_budget]:
        seed = f"{today.isoformat()}|{candidate['entity_name']}|urgent_news_baseline_gap"
        request = {
            "request_id": "rr-" + hashlib.sha256(seed.encode()).hexdigest()[:16],
            "cycle_type": "routine_research",
            "priority": "urgent_news_baseline_gap",
            "trigger_cycle": "daily_intelligence_monitoring",
            "entity_name": candidate["entity_name"],
            "entity_id": candidate["entity_id"],
            "entity_type": candidate["entity_type"],
            "baseline_coverage": candidate["baseline_coverage"],
            "trigger_sources": candidate["trigger_sources"],
            "research_lane": candidate["research_lane"],
            "signal_intensity": candidate["signal_intensity"],
            "strategic_value": candidate["strategic_value"],
            "opportunity_score": candidate["opportunity_score"],
            "queued_at": _now_iso(),
            "status": "pending",
        }
        _append(REQUESTS_PATH, request)
        queued.append(request)

    report = {
        "date": today.isoformat(), "generated_at": _now_iso(),
        "material_entities_checked": sum(1 for row in detected.values() if row.get("material")),
        "baseline_gaps_found": len(candidates), "urgent_requests_queued": len(queued),
        "daily_research_budget": daily_budget,
        "max_research_budget": MAX_RESEARCH_BUDGET,
        "already_queued_today": already_queued_today,
        "coverage_matrix": candidates,
        "queued": queued,
    }
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    result = run(date.fromisoformat(args.date) if args.date else date.today())
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
