#!/usr/bin/env python3
"""
protocol_index.py — generate system/protocols/index.json from protocol frontmatter.

Each protocol .md file in `system/protocols/` carries YAML frontmatter declaring
its script, cache file, read set, write set, inputs, and trigger. This script
parses all of them and writes a single small JSON file that a cold-start session
can consume in one read to learn the available capabilities.

Usage:
    python3 protocol_index.py             # write index.json
    python3 protocol_index.py --dry-run   # print to stdout
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rb_core as core

PROTOCOLS_DIR = core.SYSTEM_DIR / "protocols"
INDEX_PATH = PROTOCOLS_DIR / "index.json"


def parse_frontmatter(text: str) -> dict | None:
    """Tiny YAML-ish parser for the frontmatter shape we use.

    We only support the limited subset our protocols emit: scalar key:value,
    list items (`- foo`), and nested objects under known keys. No external
    YAML dependency to keep the scripts dependency-free.
    """
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    body = text[3:end].strip()

    out: dict = {}
    current_list_key: str | None = None
    current_obj_list_key: str | None = None
    current_obj: dict | None = None
    for raw in body.splitlines():
        if not raw.strip():
            continue
        if raw.startswith("  - "):
            # list item, possibly start of inline-object list
            item = raw[4:].strip()
            if current_list_key and ":" not in item:
                out[current_list_key].append(item)
            elif current_obj_list_key:
                # start a new object in an object-list
                if current_obj is not None:
                    out[current_obj_list_key].append(current_obj)
                current_obj = {}
                k, _, v = item.partition(":")
                current_obj[k.strip()] = v.strip()
        elif raw.startswith("    "):
            # continuation of an object inside an object-list
            if current_obj is not None:
                k, _, v = raw.strip().partition(":")
                current_obj[k.strip()] = v.strip()
        elif raw.startswith("- "):
            # top-level list element (no key context — rare)
            continue
        else:
            # flush any open object
            if current_obj is not None and current_obj_list_key:
                out[current_obj_list_key].append(current_obj)
                current_obj = None
            k, _, v = raw.partition(":")
            k = k.strip()
            v = v.strip()
            if v == "":
                # opens a list or object-list
                out[k] = []
                current_list_key = k
                current_obj_list_key = k
            elif v == "[]":
                out[k] = []
                current_list_key = None
                current_obj_list_key = None
            else:
                out[k] = v
                current_list_key = None
                current_obj_list_key = None
    if current_obj is not None and current_obj_list_key:
        out[current_obj_list_key].append(current_obj)
    return out


def build_index() -> dict:
    protocols = []
    for p in sorted(PROTOCOLS_DIR.glob("P-*.md")):
        fm = parse_frontmatter(p.read_text())
        if not fm:
            continue
        fm["file"] = f"system/protocols/{p.name}"
        protocols.append(fm)
    return {
        "version": 1,
        "count": len(protocols),
        "protocols": protocols,
        "_notes": (
            "Generated by system/scripts/protocol_index.py from each protocol's "
            "YAML frontmatter. Cold-start sessions should load this file (one "
            "small JSON) instead of scanning the protocols/ directory."
        ),
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    idx = build_index()
    if args.dry_run:
        print(json.dumps(idx, indent=2))
        return 0
    INDEX_PATH.write_text(json.dumps(idx, indent=2) + "\n")
    print(f"Wrote {INDEX_PATH.relative_to(core.PROJECT_DIR)} "
          f"({idx['count']} protocols).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
