#!/usr/bin/env python3
"""
session_index.py — scan system/_sessions/*.md and produce index.json.

The cold-start path consumes index.json (small) to know which sessions
are recent and what they touched, without parsing every .md body.

Usage:
    python3 session_index.py             # write index.json
    python3 session_index.py --dry-run   # print to stdout
    python3 session_index.py --limit 5   # only the latest N in the index
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rb_core as core

SESSIONS_DIR = core.SYSTEM_DIR / "_sessions"
INDEX_PATH = SESSIONS_DIR / "index.json"


def _parse_frontmatter(text: str) -> dict | None:
    """Re-use the protocol-index parser by going through PyYAML if available,
    falling back to the tiny parser. Frontmatter only — body discarded."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    body = text[3:end].strip()
    return core._yaml_load(body)


def build_index(limit: int | None = None) -> dict:
    files = sorted(
        (p for p in SESSIONS_DIR.glob("*.md") if not p.stem.startswith("_") and p.stem != "README"),
        key=lambda p: p.stem,
        reverse=True,
    )
    if limit is not None:
        files = files[:limit]
    sessions = []
    for p in files:
        fm = _parse_frontmatter(p.read_text()) or {}
        if not fm:
            continue
        sessions.append({
            "session_id": fm.get("session_id", p.stem),
            "date": fm.get("date"),
            "end_time": fm.get("end_time"),
            "focus_areas": fm.get("focus_areas") or [],
            "threads_touched": fm.get("threads_touched") or [],
            "contacts_touched": fm.get("contacts_touched") or [],
            "mutations": fm.get("mutations") or {},
            "status": fm.get("status"),
            "next_session_should": fm.get("next_session_should"),
            "file": f"system/_sessions/{p.name}",
        })
    return {
        "version": 1,
        "count": len(sessions),
        "sessions": sessions,
        "_notes": (
            "Generated by system/scripts/session_index.py. Sessions are ordered "
            "newest first. Cold-start sessions should read the top 2-3 entries "
            "to pick up where the last session left off."
        ),
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--limit", type=int, default=None)
    args = p.parse_args()
    idx = build_index(limit=args.limit)
    if args.dry_run:
        print(json.dumps(idx, indent=2))
        return 0
    SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(json.dumps(idx, indent=2) + "\n")
    rel = INDEX_PATH.relative_to(core.PROJECT_DIR)
    print(f"Wrote {rel} ({idx['count']} sessions).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
