#!/usr/bin/env python3
"""team_artifact_footer.py — shared provenance footer for Team Portal exports.

Every artifact the Team Portal hands a teammate (Blue Sheet download, Green
Sheet preview/download/email, a future export type) needs the same
disclosure: who generated it, when, how current the underlying data is,
that it's a working draft (never the canonical account document), and that
judgment fields still need a human. Implemented once here so it isn't
reinvented — and drifted — per artifact type, the same reasoning that put
versioning in one shared artifact_vault_common.py rather than one copy per
artifact script.
"""
from __future__ import annotations

import datetime
from typing import Optional


def stamp_markdown(
    markdown: str,
    *,
    generated_by: str,
    data_as_of: Optional[str] = None,
    source_confidence_note: Optional[str] = None,
) -> str:
    """Append the standard footer block to already-rendered Markdown."""
    lines = [
        "",
        "---",
        "",
        f"*Generated by: {generated_by}*",
        f"*Generated date: {_now_date()}*",
    ]
    if data_as_of:
        lines.append(f"*Data as of: {data_as_of}*")
    lines.append("*Working draft — not a canonical account document.*")
    if source_confidence_note:
        lines.append(f"*{source_confidence_note}*")
    lines.append("*Requires human validation before use with a customer.*")
    return markdown.rstrip() + "\n" + "\n".join(lines) + "\n"


def footer_fields(
    *,
    generated_by: str,
    data_as_of: Optional[str] = None,
    source_confidence_note: Optional[str] = None,
) -> dict:
    """Same disclosure, as structured fields — for JSON responses (Blue
    Sheet coverage report, News/Earnings payloads) where a Markdown block
    doesn't apply."""
    return {
        "generated_by": generated_by,
        "generated_date": _now_date(),
        "data_as_of": data_as_of,
        "working_draft": True,
        "source_confidence_note": source_confidence_note,
        "requires_human_validation": True,
    }


def _now_date() -> str:
    return datetime.date.today().isoformat()
