"""
test_openapi_gpt_capture_relay_schema.py — RB-2026-09-21.

system/api/openapi_gpt_capture_relay.yaml is a hand-written OpenAPI schema
for the new RB Capture Relay Custom GPT (RBB_TOKEN_EFFICIENT_ARCHITECTURE_
SCOPE_2026-09-19.md, Phase 1 build-order item 3) -- deliberately NOT
generated by validate_openapi_gpt.py (that tool governs the separate,
30-operation openapi_gpt.yaml for a different, retired GPT surface). Being
hand-written and unvalidated by that tooling means it can silently drift
from the real /captures/queue-text endpoint with nothing to catch it --
the same class of risk the KB documentation drift audit found and fixed
elsewhere in this system. This test is that guard: it compares the
schema's declared request fields directly against server.py's real
QueueCaptureTextBody Pydantic model, not against a second hand-maintained
copy of the field list.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = ROOT / "system" / "api" / "openapi_gpt_capture_relay.yaml"
sys.path.insert(0, str(ROOT / "system" / "scripts"))
sys.path.insert(0, str(ROOT / "system" / "api"))


class TestCaptureRelaySchemaValid(unittest.TestCase):
    def setUp(self):
        self.spec = yaml.safe_load(SCHEMA_PATH.read_text(encoding="utf-8"))

    def test_yaml_parses_as_a_single_document(self):
        self.assertIsInstance(self.spec, dict)
        self.assertEqual(self.spec.get("openapi"), "3.1.0")

    def test_every_description_field_is_under_gpt_builder_300_char_limit(self):
        """RB-2026-09-22: confirmed live -- ChatGPT's GPT Builder rejected
        this schema on import with 'description has length 364 exceeding
        limit of 300' on the operation description. Guards every
        `description` field in the document (not just the one that was
        caught), so a future edit can't silently push a different one back
        over the same limit."""
        overlong = []

        def walk(obj, path=""):
            if isinstance(obj, dict):
                for key, value in obj.items():
                    sub_path = f"{path}.{key}" if path else key
                    if key == "description" and isinstance(value, str) and len(value) > 300:
                        overlong.append((sub_path, len(value)))
                    walk(value, sub_path)
            elif isinstance(obj, list):
                for i, value in enumerate(obj):
                    walk(value, f"{path}[{i}]")

        walk(self.spec)
        self.assertEqual(overlong, [], f"description field(s) over GPT Builder's 300-char limit: {overlong}")

    def test_exactly_one_path_queue_text(self):
        self.assertEqual(list(self.spec["paths"].keys()), ["/captures/queue-text"])

    def test_operation_id_matches_real_endpoint(self):
        import server as srv
        op = self.spec["paths"]["/captures/queue-text"]["post"]
        self.assertEqual(op["operationId"], "queueCaptureText")
        # The real route must actually exist with this same operation_id --
        # confirms this isn't just an internally-consistent typo.
        matching = [
            route for route in srv.app.routes
            if getattr(route, "path", None) == "/captures/queue-text" and "POST" in getattr(route, "methods", set())
        ]
        self.assertTrue(matching, "no live POST /captures/queue-text route found in server.py")
        self.assertEqual(matching[0].operation_id, "queueCaptureText")

    def test_auth_header_matches_real_auth_convention(self):
        scheme = self.spec["components"]["securitySchemes"]["ApiKeyAuth"]
        self.assertEqual(scheme["type"], "apiKey")
        self.assertEqual(scheme["in"], "header")
        self.assertEqual(scheme["name"], "x-api-key")

    def test_request_body_fields_match_real_pydantic_model(self):
        import server as srv
        schema_fields = set(self.spec["components"]["schemas"]["QueueCaptureTextBody"]["properties"].keys())
        real_fields = set(srv.QueueCaptureTextBody.model_fields.keys())
        self.assertEqual(
            schema_fields, real_fields,
            f"schema/model field drift: schema-only={schema_fields - real_fields}, model-only={real_fields - schema_fields}",
        )

    def test_required_fields_match_real_pydantic_model(self):
        import server as srv
        schema_required = set(self.spec["components"]["schemas"]["QueueCaptureTextBody"].get("required") or [])
        real_required = {
            name for name, field in srv.QueueCaptureTextBody.model_fields.items() if field.is_required()
        }
        self.assertEqual(schema_required, real_required)

    def test_capture_type_enum_matches_real_allowed_values(self):
        import server as srv
        schema_enum = set(
            self.spec["components"]["schemas"]["QueueCaptureTextBody"]["properties"]["capture_type"]["enum"]
        )
        self.assertEqual(schema_enum, srv.QUEUE_CAPTURE_TEXT_TYPES)


if __name__ == "__main__":
    unittest.main()
